cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/hong/expertn50/dev/.waf-1.7.9-894b00a4b806519bb5e04ddc9eff1714/waflib/Tools/c_config.py", line 459, in run_c_code\n    bld.compile()\n  File "/home/hong/expertn50/dev/.waf-1.7.9-894b00a4b806519bb5e04ddc9eff1714/waflib/Build.py", line 198, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 139696198421520: c test.c -> test.c.1.o}\n[\'/usr/bin/gcc\', \'-Wall\', \'-fPIC\', \'-g\', \'-O0\', \'-DHAVE_GLIB=1\', \'-DHAVE_GOBJECT=1\', \'-DHAVE_GMODULE=1\', \'-DHAVE_LIBXML2=1\', \'-DXPN_WITHOUT_DATABASE=1\', \'-DXPN_VERSION="5.0 Rev 0"\', \'-DXPN_DEBUG=1\', \'-DUSE_MPI=1\', \'../test.c\', \'-c\', \'-o\', \'test.c.1.o\']\n'
